### ISSUE TITLE
err for f2c.h

### ISSUE THREAD

**Issue by kevin-ni** [simonlynen/android_libs#1]
$ $NDK/ndk-build
Compile thumb  : clapack <= sgbbrd.c
In file included from F:/rtkgps/jni/simonlynen_android_libs/lapack/jni/clapack/SRC/sgbbrd.c:13:0:
F:/rtkgps/jni/simonlynen_android_libs/lapack/jni/clapack/SRC/f2c.h:1:1: error: expected identifier or '(' before '.' token

**Comment by simonlynen** [comment]
Hi Kevin,

the file https://github.com/simonlynen/android_libs/blob/master/lapack/jni/clapack/SRC/f2c.h is a symlink to https://github.com/simonlynen/android_libs/blob/master/lapack/jni/clapack/INCLUDE/f2c.h . This is apparently the case for the original sources of clapack too. 

Since you seem to be using Windows this symlink could not be created correctly by git. If you want to use this package on Windows, you might have to replace these symlinks with proper include directives.

E.g. create a textfile https://github.com/simonlynen/android_libs/blob/master/lapack/jni/clapack/SRC/f2c.h containing:

```
#include "../INCLUDE/f2c.h"
```

You might want to check for other such cases and apply similar fixes. If you want you can create a pullrequest for these changes, which I would appreciate a lot.

Thanks

**Comment by simonlynen** [comment]
Also make sure to check out http://slynenandroid.wordpress.com/ for additional android hints which cover quite some issues.

**Comment by kevin-ni** [comment]
I modified all the files by adding keyword include. It's a slow but effective way. Thanks.
